help=["Here are available commands :",
"[optional parameter] <mandatory one>",
"/help : Display this help, use j/k to navigate and q to quit.",
"/quit [message] : Quit with an optional [message].",
"/clear : Clear what is displayed on your screen.",
"/timestamp <on|off> : Enable/disable line timestamping.",
"/nickname <newNickname> : Change your nickname.",
"/channel <newChannelName> : Switch channel.",
"/pm <id> <message> : Send a private message to the user with the id <id>",
"/history [on|off|clear] : With no argument, display the last 50 message.",
"/bug <message> : Send a bug / suggestion report.",
"/list : List peoples in channel.",
"/afk : Toggle afk.",
"/notif : Toggle visual flash notification on new message."]
