help=["Here are available commands :",
"[optional parameter] <mandatory one>",
" ",
"/help : Display this help, use j/k to navigate and q to quit.",
"/list : List peoples in channel.",
"/clear : Clear your screen.",
"/paste : Enter paste mode, usefull for pasting long links.",
" ",
"/quit [message] : Quit with an optional [message].",
"/history [on|off|clear] : With no argument, display the last 100 message.",
" ",
"/nickname <newNickname> : Change your nickname.",
"/channel <newChannelName> : Switch channel.",
"/pm <id> <message> : Send a private message to the user with the id <id>",
"/bug <message> : Send a bug / suggestion report.",
" ",
"/timestamp <on|off> : Enable/disable line timestamping.",
"/notif <on|off> : Toggle visual flash notification on new message.",
"/afk : Toggle afk.",
"/encrypt <on|off> : Toggle encryption."]
