help=["Here are available commands :",
"[optional parameter] <mandatory one>",
" ",
"/help : Display this help, use j/k to navigate and q to quit.",
"/list : List peoples in channel.",
"/clear : Clear your screen.",
"/paste : Enter paste mode, usefull for pasting long links.",
"/me : It's you :)",
" ",
"/quit [message] : Quit with an optional [message].",
"/history [on|off|clear|newLength] : With no argument, display the last 100 message.",
" ",
"/nickname <newNickname> : Change your nickname.",
"/channel <newChannelName> : Switch channel.",
"/pm <id> <message> : Send a private message to the user with the id <id>",
"/bug <message> : Send a bug / suggestion report.",
" ",
"/timestamp <on|off> : Enable/disable line timestamping.",
"/notif <on|off> [flashInterval]: Toggle visual flash notification on new message.",
"/afk <on|off> : Toggle afk.",
"/encrypt <on|off> : Toggle encryption."]

commands=[["a","afk"],
["af","afk"],
["afk","afk"],
["b","bug"],
["bu","bug"],
["bug","bug"],
["ch","channel"],
["cha","channel"],
["chan","channel"],
["chann","channel"],
["channel","channel"],
["cl","clear"],
["cle","clear"],
["clea","clear"],
["clear","clear"],
["e","encrypt"],
["en","encrypt"],
["enc","encrypt"],
["encr","encrypt"],
["encry","encrypt"],
["encryp","encrypt"],
["encrypt","encrypt"],
["he","help"],
["hel","help"],
["help","help"],
["hi","history"],
["his","history"],
["hist","history"],
["histo","history"],
["histor","history"],
["history","history"],
["i","id"],
["id","id"],
["l","list"],
["li","list"],
["lis","list"],
["list","list"],
["m","me"],
["me","me"],
["ni","nickname"],
["nic","nickname"],
["nick","nickname"],
["nickn","nickname"],
["nickna","nickname"],
["nicknam","nickname"],
["nickname","nickname"],
["no","notif"],
["not","notif"],
["noti","notif"],
["notif","notif"],
["pa","paste"],
["pas","paste"],
["past","paste"],
["paste","paste"],
["pl","plop"],
["plo","plop"],
["plop","plop"],
["pm","pm"],
["q","quit"],
["qu","quit"],
["qui","quit"],
["quit","quit"],
["t","timestamp"],
["ti","timestamp"],
["tim","timestamp"],
["time","timestamp"],
["times","timestamp"],
["timesta","timestamp"],
["timestam","timestamp"],
["timestamp","timestamp"]]

