#!/bin/bash
#sigdecoparcebatarddessh
#refaire key.py avec des boucle et wait pour windob
#autocompletion
#verifier le user qui lance sschat
#curses.flash / sur une window
#Need aussi de revoir le system de gestion des nick id
#switch channel
#motbye
#color
#patch curses pour l'insert

