#!/usr/bin/python
import minion, curses, curses.textpad, signal, sys, time

class SschatScreen:
	def __init__(self):
	#Initialize screen
		self.mainWindow=curses.initscr()
		self.ySize, self.xSize = self.mainWindow.getmaxyx()
		self.titleWindow = curses.newwin(1, self.xSize, 0, 0)
		self.conversWindow = curses.newwin((self.ySize - 2), self.xSize, 1, 0)
                self.inputWindow = curses.newwin(1, (self.xSize - 1), (self.ySize - 1), 1)
		self.inputBox = curses.textpad.Textbox(self.inputWindow)
		self.inputBox.stripspaces=1
		self.conversWindow.scrollok(True)
		self.mainWindow.addch((self.ySize - 1),0,">")
#		self.conversWindow.bkgd(' ', curses.COLOR_BLUE)
#		self.titleWindow.bkgd(' ', curses.COLOR_RED)
		curses.noecho()
		self.mainWindow.refresh()
                self.currentY=0
	
	def printMessage(self, message):
	#Print a message to the screen conversWindow
#                if self.currentY >= (self.ySize - 2) :
#                        self.clearConversWindow()
#			self.currentY=0
#                self.conversWindow.addstr( self.currentY, 0, message)
#                self.conversWindow.refresh()
#                self.currentY = self.currentY+1
                self.conversWindow.addstr(message+"\n")
                self.conversWindow.refresh()

	def getInput(self):
	#Get input from the keyboard from inputWindow
		while 1:
			inputMessage = self.inputBox.edit()
			if inputMessage != "":
				self.inputWindow.clear()
				self.inputWindow.refresh()
				return inputMessage[:-1] # cette methode d'input ajoute un espace a la fin
#		while 1:
#	                inputMessage = self.inputWindow.getstr(1,0)
#			if inputMessage != "":
#	        	        self.inputWindow.clear()
#        		        return inputMessage
	
	def clearConversWindow(self):
	#Clear the conversation screen
		self.conversWindow.clear()
                self.currentY = 0
		self.conversWindow.refresh()

	def setTitleWindow(self, title):
	#Set the title screen
		self.titleWindow.clear()
		self.titleWindow.addstr(title)
		self.titleWindow.refresh()

class SschatUser:
	def __init__(self, username):
		self.userName= username

class SschatMinion(minion.Minion):
        def handlerAddMinion(self, pid):
        #Called when a minion registers in the workspace
                self.peers.append(pid)
                self.screen.setTitleWindow(str(self.workspace)+" with "+str(len(self.peers)))

        def handlerRemMinion(self, pid):
        #Called when a minion leaves the workspace
                self.peers.remove(pid)
                self.screen.setTitleWindow(str(self.workspace)+" with "+str(len(self.peers)))

	def handlerMessage(self, message):
	#redef
		self.screen.printMessage(message)

	def cleanQuit(self):
	#redef
		minion.Minion.cleanQuit(self)
		curses.endwin()
		print "Bye !"
	
	def initSignals(self):
	#redef
		minion.Minion.initSignals(self)
                signal.signal(signal.SIGWINCH, self.handlerResize)

	def handlerResize(self, signum, frame):
		self.screen.inputBox = ""
		self.screen = None
		curses.endwin()
		self.screen = SschatScreen()
#		self.screen.setTitleWindow("You are in channel : "+str(self.workspace)+" with "+str(len(self.peers))+" other people")
		self.screen.setTitleWindow(str(self.workspace)+" with "+str(len(self.peers)))

	def graphicalInit(self):
	#Asking questions that need to be asked
		self.screen=SschatScreen()
		if len(sys.argv) > 1:
			self.init(sys.argv[1])
			self.user=SschatUser(sys.argv[2])
		else:
			self.screen.printMessage("Hey what's the channel you're looking for ?")
			self.init(self.screen.getInput())
			self.screen.printMessage("Hey what's your nickname ?")
			self.user=SschatUser(self.screen.getInput())

		self.screen.clearConversWindow()
#		self.screen.setTitleWindow("You are in channel : "+str(self.workspace)+" with "+str(len(self.peers))+" other people")
		self.screen.setTitleWindow(str(self.workspace)+" with "+str(len(self.peers)))

	def main(self):
	#redef
                while 1:
                        chatMessage= self.screen.getInput()
                        if chatMessage != "":
                                chatMessage= self.user.userName+" ("+str(self.myPid)+") : "+chatMessage
                                self.screen.printMessage(chatMessage)
                                self.sendMessage("/msg "+chatMessage)

jaune=SschatMinion()
jaune.graphicalInit()
jaune.main()
